# Generated by Django 5.2.13 on 2026-04-30 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('popia_consent', models.BooleanField(default=False)),
                ('not_medical_advice_acknowledged', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('smokes', models.BooleanField(default=False)),
                ('alcohol', models.CharField(choices=[('none', 'None'), ('moderate', 'Moderate'), ('high', 'High')], default='none', max_length=10)),
                ('exercise', models.CharField(choices=[('none', 'None'), ('low', '1-2x per week'), ('high', '3+ per week')], default='none', max_length=10)),
                ('frequent_headaches', models.BooleanField(default=False)),
                ('dizziness', models.BooleanField(default=False)),
                ('blurred_vision', models.BooleanField(default=False)),
                ('frequent_urination', models.BooleanField(default=False)),
                ('excessive_thirst', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('family_diabetes', models.BooleanField(default=False)),
                ('family_hypertension', models.BooleanField(default=False)),
                ('previously_diagnosed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bmi', models.FloatField()),
                ('diabetes_score', models.IntegerField()),
                ('hypertension_score', models.IntegerField()),
                ('diabetes_risk', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('hypertension_risk', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('diabetes_recommendation', models.TextField()),
                ('hypertension_recommendation', models.TextField()),
                ('key_risk_factors', models.JSONField(default=list)),
                ('next_steps', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
            ],
        ),
    ]
