# Generated by Django 5.2.13 on 2026-04-30 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.assessment'),
        ),
    ]
